In [2]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from functools import reduce
%matplotlib inline

In [3]:
#need to make sure you keep all of your source data close at hand so you can cite your sources....

reading in my data on elections from 1976..each table represents data for the named elections from the years in the comments

In [4]:
#US House 1976-2018
house = pd.read_csv('../data/1976-2018-house3.csv')

In [5]:
# house.info()

In [6]:
# house.head()

In [7]:
# house.tail()

In [8]:
#US Senate 1976-2020
senate = pd.read_csv('../data/1976-2020-senate.csv')

In [9]:
# senate.info()

In [10]:
# senate.head()

In [11]:
# senate.tail()

In [12]:
#US president 1976-2020
president = pd.read_csv('../data/1976-2020-president.csv')

In [13]:
# president.info()

In [14]:
# president.head()

In [15]:
# president.tail()

In [16]:
#county returns president 2000-2016
county_pres = pd.read_csv('../data/countypres_2000-2016.csv')

In [17]:
county_pres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50524 entries, 0 to 50523
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            50524 non-null  int64
 1   state           50524 non-null  object
 2   state_po        50460 non-null  object
 3   county          50524 non-null  object
 4   FIPS            50476 non-null  float64
 5   office          50524 non-null  object
 6   candidate       50524 non-null  object
 7   party           34735 non-null  object
 8   candidatevotes  50120 non-null  float64
 9   totalvotes      50524 non-null  int64
 10  version         50524 non-null  int64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.2+ MB

In [18]:
county_pres.head()

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
0,2000,Alabama,AL,Autauga,1001.0,President,Al Gore,democrat,4942.0,17208,20191203
1,2000,Alabama,AL,Autauga,1001.0,President,George W. Bush,republican,11993.0,17208,20191203
2,2000,Alabama,AL,Autauga,1001.0,President,Ralph Nader,green,160.0,17208,20191203
3,2000,Alabama,AL,Autauga,1001.0,President,Other,NaN,113.0,17208,20191203
4,2000,Alabama,AL,Baldwin,1003.0,President,Al Gore,democrat,13997.0,56480,20191203

In [19]:
county_pres.tail()

,year,state,state_po,county,FIPS,office,candidate,party,candidatevotes,totalvotes,version
50519,2016,Alaska,AK,District 40,2040.0,President,Donald Trump,republican,1377.0,4610,20191203
50520,2016,Alaska,AK,District 40,2040.0,President,Other,NaN,895.0,4610,20191203
50521,2016,Alaska,NaN,District 99,2099.0,President,Hillary Clinton,democrat,274.0,5056,20191203
50522,2016,Alaska,NaN,District 99,2099.0,President,Donald Trump,republican,40.0,5056,20191203
50523,2016,Alaska,NaN,District 99,2099.0,President,Other,NaN,28.0,5056,20191203

reading in census data for elections by year

In [20]:
reg_sex_state_2010 = pd.read_excel('../data/registration_race_sex_state_2010.xls',header = 2)

In [21]:
#this is going to need some cleaning....cool.
# reg_sex_state_2010.info()

In [22]:
#population of 18yo +in thousands 

# reg_sex_state_2010.head(15)

In [23]:
#bottom of table contains some (un)helpful info that should have been in a readme file. 

# reg_sex_state_2010.tail(100)

In [24]:
#tx voting population 18years+

tx_reg_2010 = pd.concat([reg_sex_state_2010.iloc[:11,:],reg_sex_state_2010.iloc[484:495,:]],axis = 0)

I messed around with the code below trying to set the header...until I found an argument to put into the read_excel function...which I thought worked like a dream but it's currently not working the way I want every time I load it...must be something with my notebook...and specifically it's the fact that I wasn't giving the DF a new variable name.  So yes, technically it was the notebook but really it was because of a user decision.

In [25]:


#tx voting population 18years+

# tx_reg_2010.columns = tx_reg_2010.iloc[1]
# tx_reg_clean = tx_reg_2010.drop(tx_reg_2010.index[1], axis = 0)

# tx_reg_2010.drop(tx_reg_2010.iloc[:1,:], axis = 0)

In [26]:
tx_reg_2010 = tx_reg_2010.rename(columns = {'Unnamed: 1': 'Race/Gender'})

In [27]:
tx_reg_2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 494
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   STATE                         2 non-null      object
 1   Race/Gender                   22 non-null     object
 2   Total Population              22 non-null     float64
 3   Total Citizen Population      22 non-null     object
 4   Total registered              22 non-null     object
 5   Percent registered
(Total)    22 non-null     object
 6   Margin of Error1              22 non-null     object
 7   Percent registered
(Citizen)  22 non-null     object
 8   Margin of Error1.1            22 non-null     object
 9   Total voted                   22 non-null     object
 10  Percent voted
(Total)         22 non-null     object
 11  Margin of Error1.2            22 non-null     object
 12  Percent voted
(Citizen)       22 non-null     object
 13  Margin of Error1.3            22 non-null     object
dtypes: float64(1), object(13)
memory usage: 2.6+ KB

In [28]:
###Not sure I'm going to use all of above but I have it....

reading in TX County Census data 2010-2019

first age data:

In [29]:
tx_census_age = pd.read_csv('../data/TX_county_census_data.csv')

In [30]:
# tx_census_age.info()

In [31]:
# tx_census_age.head()

In [32]:
# tx_census_age.tail()

In [33]:
#tried all of the below to drop columns which didn't work but I finally found something that did...

tx_age = pd.concat([tx_census_age.iloc[:,:9],tx_census_age.iloc[:,18:21],tx_census_age.iloc[:,24:27],
                  tx_census_age.iloc[:,36:39],tx_census_age.iloc[:,90:]],axis = 1)

# tx_census_age.drop(tx_census_age.columns[[1]], axis = 1)
# tx_age = tx_census_age.drop(list(range(9,19)), axis = 1)

# tx_census_age.drop(tx_census_age.iloc[:,21:23], axis = 1)
# tx_census_age.drop(tx_census_age.iloc[:,28:35], axis = 1)
# tx_census_age.drop(tx_census_age.iloc[:,38:77], inplace = True, axis = 1)

In [34]:
tx_age.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3048 entries, 0 to 3047
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SUMLEV           3048 non-null   int64
 1   STATE            3048 non-null   int64
 2   COUNTY           3048 non-null   int64
 3   STNAME           3048 non-null   object
 4   CTYNAME          3048 non-null   object
 5   YEAR             3048 non-null   int64
 6   POPESTIMATE      3048 non-null   int64
 7   POPEST_MALE      3048 non-null   int64
 8   POPEST_FEM       3048 non-null   int64
 9   AGE1824_TOT      3048 non-null   int64
 10  AGE1824_MALE     3048 non-null   int64
 11  AGE1824_FEM      3048 non-null   int64
 12  AGE18PLUS_TOT    3048 non-null   int64
 13  AGE18PLUS_MALE   3048 non-null   int64
 14  AGE18PLUS_FEM    3048 non-null   int64
 15  AGE65PLUS_TOT    3048 non-null   int64
 16  AGE65PLUS_MALE   3048 non-null   int64
 17  AGE65PLUS_FEM    3048 non-null   int64
 18  AGE85PLUS_TOT    3048 non-null   int64
 19  AGE85PLUS_MALE   3048 non-null   int64
 20  AGE85PLUS_FEM    3048 non-null   int64
 21  MEDIAN_AGE_TOT   3048 non-null   float64
 22  MEDIAN_AGE_MALE  3048 non-null   float64
 23  MEDIAN_AGE_FEM   3048 non-null   float64
dtypes: float64(3), int64(19), object(2)
memory usage: 571.6+ KB

In [35]:
# tx_age

reading TX census race data

In [36]:
tx_census_race = pd.read_csv('../data/TX_age_sex_race.csv')

I'm including these for my own use:


The key for the YEAR variable is as follows:
1 = 4/1/2010 Census population
2 = 4/1/2010 population estimates base
3 = 7/1/2010 population estimate
4 = 7/1/2011 population estimate
5 = 7/1/2012 population estimate
6 = 7/1/2013 population estimate
7 = 7/1/2014 population estimate
8 = 7/1/2015 population estimate
9 = 7/1/2016 population estimate
10 = 7/1/2017 population estimate
11 = 7/1/2018 population estimate
12 = 7/1/2019 population estimate


The key for AGEGRP is as follows:
0 = Total
1 = Age 0 to 4 years
2 = Age 5 to 9 years
3 = Age 10 to 14 years
4 = Age 15 to 19 years
5 = Age 20 to 24 years
6 = Age 25 to 29 years
7 = Age 30 to 34 years
8 = Age 35 to 39 years
9 = Age 40 to 44 years
10 = Age 45 to 49 years
11 = Age 50 to 54 years
12 = Age 55 to 59 years
13 = Age 60 to 64 years
14 = Age 65 to 69 years
15 = Age 70 to 74 years
16 = Age 75 to 79 years
17 = Age 80 to 84 years
18 = Age 85 years or older

In [37]:
tx_census_race.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57912 entries, 0 to 57911
Data columns (total 80 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SUMLEV        57912 non-null  int64
 1   STATE         57912 non-null  int64
 2   COUNTY        57912 non-null  int64
 3   STNAME        57912 non-null  object
 4   CTYNAME       57912 non-null  object
 5   YEAR          57912 non-null  int64
 6   AGEGRP        57912 non-null  int64
 7   TOT_POP       57912 non-null  int64
 8   TOT_MALE      57912 non-null  int64
 9   TOT_FEMALE    57912 non-null  int64
 10  WA_MALE       57912 non-null  int64
 11  WA_FEMALE     57912 non-null  int64
 12  BA_MALE       57912 non-null  int64
 13  BA_FEMALE     57912 non-null  int64
 14  IA_MALE       57912 non-null  int64
 15  IA_FEMALE     57912 non-null  int64
 16  AA_MALE       57912 non-null  int64
 17  AA_FEMALE     57912 non-null  int64
 18  NA_MALE       57912 non-null  int64
 19  NA_FEMALE     57912 non-null  int64
 20  TOM_MALE      57912 non-null  int64
 21  TOM_FEMALE    57912 non-null  int64
 22  WAC_MALE      57912 non-null  int64
 23  WAC_FEMALE    57912 non-null  int64
 24  BAC_MALE      57912 non-null  int64
 25  BAC_FEMALE    57912 non-null  int64
 26  IAC_MALE      57912 non-null  int64
 27  IAC_FEMALE    57912 non-null  int64
 28  AAC_MALE      57912 non-null  int64
 29  AAC_FEMALE    57912 non-null  int64
 30  NAC_MALE      57912 non-null  int64
 31  NAC_FEMALE    57912 non-null  int64
 32  NH_MALE       57912 non-null  int64
 33  NH_FEMALE     57912 non-null  int64
 34  NHWA_MALE     57912 non-null  int64
 35  NHWA_FEMALE   57912 non-null  int64
 36  NHBA_MALE     57912 non-null  int64
 37  NHBA_FEMALE   57912 non-null  int64
 38  NHIA_MALE     57912 non-null  int64
 39  NHIA_FEMALE   57912 non-null  int64
 40  NHAA_MALE     57912 non-null  int64
 41  NHAA_FEMALE   57912 non-null  int64
 42  NHNA_MALE     57912 non-null  int64
 43  NHNA_FEMALE   57912 non-null  int64
 44  NHTOM_MALE    57912 non-null  int64
 45  NHTOM_FEMALE  57912 non-null  int64
 46  NHWAC_MALE    57912 non-null  int64
 47  NHWAC_FEMALE  57912 non-null  int64
 48  NHBAC_MALE    57912 non-null  int64
 49  NHBAC_FEMALE  57912 non-null  int64
 50  NHIAC_MALE    57912 non-null  int64
 51  NHIAC_FEMALE  57912 non-null  int64
 52  NHAAC_MALE    57912 non-null  int64
 53  NHAAC_FEMALE  57912 non-null  int64
 54  NHNAC_MALE    57912 non-null  int64
 55  NHNAC_FEMALE  57912 non-null  int64
 56  H_MALE        57912 non-null  int64
 57  H_FEMALE      57912 non-null  int64
 58  HWA_MALE      57912 non-null  int64
 59  HWA_FEMALE    57912 non-null  int64
 60  HBA_MALE      57912 non-null  int64
 61  HBA_FEMALE    57912 non-null  int64
 62  HIA_MALE      57912 non-null  int64
 63  HIA_FEMALE    57912 non-null  int64
 64  HAA_MALE      57912 non-null  int64
 65  HAA_FEMALE    57912 non-null  int64
 66  HNA_MALE      57912 non-null  int64
 67  HNA_FEMALE    57912 non-null  int64
 68  HTOM_MALE     57912 non-null  int64
 69  HTOM_FEMALE   57912 non-null  int64
 70  HWAC_MALE     57912 non-null  int64
 71  HWAC_FEMALE   57912 non-null  int64
 72  HBAC_MALE     57912 non-null  int64
 73  HBAC_FEMALE   57912 non-null  int64
 74  HIAC_MALE     57912 non-null  int64
 75  HIAC_FEMALE   57912 non-null  int64
 76  HAAC_MALE     57912 non-null  int64
 77  HAAC_FEMALE   57912 non-null  int64
 78  HNAC_MALE     57912 non-null  int64
 79  HNAC_FEMALE   57912 non-null  int64
dtypes: int64(78), object(2)
memory usage: 35.3+ MB

In [38]:
# tx_census_race.head(20)

In [39]:
# tx_census_race.tail()

In [40]:
#creating a table of the census race data I think I need:
tx_race = pd.concat([tx_census_race.iloc[:,:18],tx_census_race.iloc[:,24:26],tx_census_race.iloc[:,28:30], 
                     tx_census_race.iloc[:,34:36],  tx_census_race.iloc[:,56:58]],axis = 1)

In [41]:
tx_race.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57912 entries, 0 to 57911
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUMLEV       57912 non-null  int64
 1   STATE        57912 non-null  int64
 2   COUNTY       57912 non-null  int64
 3   STNAME       57912 non-null  object
 4   CTYNAME      57912 non-null  object
 5   YEAR         57912 non-null  int64
 6   AGEGRP       57912 non-null  int64
 7   TOT_POP      57912 non-null  int64
 8   TOT_MALE     57912 non-null  int64
 9   TOT_FEMALE   57912 non-null  int64
 10  WA_MALE      57912 non-null  int64
 11  WA_FEMALE    57912 non-null  int64
 12  BA_MALE      57912 non-null  int64
 13  BA_FEMALE    57912 non-null  int64
 14  IA_MALE      57912 non-null  int64
 15  IA_FEMALE    57912 non-null  int64
 16  AA_MALE      57912 non-null  int64
 17  AA_FEMALE    57912 non-null  int64
 18  BAC_MALE     57912 non-null  int64
 19  BAC_FEMALE   57912 non-null  int64
 20  AAC_MALE     57912 non-null  int64
 21  AAC_FEMALE   57912 non-null  int64
 22  NHWA_MALE    57912 non-null  int64
 23  NHWA_FEMALE  57912 non-null  int64
 24  H_MALE       57912 non-null  int64
 25  H_FEMALE     57912 non-null  int64
dtypes: int64(24), object(2)
memory usage: 11.5+ MB

In [42]:
# for index, row in tx_race.iterrows():
#     if row['AGEGRP'] > 0:
#         tx_race.drop(index, inplace=True)

#trying to remove all agegrp but the total
tx_race = tx_race[tx_race.AGEGRP == 0]

In [43]:
# tx_race.head()

In [44]:
# tx_race.tail()

In [45]:
#Thinking that I might need to use the not-hispanic white alone numbers to get what I'm looking for....
#NHWA_MALE Not Hispanic, White alone male population
#NHWA_FEMALE Not Hispanic, White alone female population
#used this code first to get the race measure I thought I needed.  

#top code is to find total number of people in each county per reporting year that identify as white alone(includes hispanic)
#tx_race['WA_POP'] = tx_race['WA_MALE'] + tx_race['WA_FEMALE']

#this code is total number of people in each county per reporting year that identify as white alone (NOT Hispanic)
tx_race['NHWA_POP'] = tx_race['NHWA_MALE'] + tx_race['NHWA_FEMALE']
#I will only need the second line but am leaving the first one in to show how I got here...
#was looking for counties with majority not white to compare with counties with Majority white

In [46]:
tx_race.head()

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,AA_FEMALE,BAC_MALE,BAC_FEMALE,AAC_MALE,AAC_FEMALE,NHWA_MALE,NHWA_FEMALE,H_MALE,H_FEMALE,NHWA_POP
0,50,48,1,Texas,Anderson County,1,0,58458,35521,22937,...,171,9346,3633,357,224,19751,16105,6363,2924,35856
19,50,48,1,Texas,Anderson County,2,0,58452,35518,22934,...,171,9346,3633,357,224,19748,16102,6363,2924,35850
38,50,48,1,Texas,Anderson County,3,0,58493,35542,22951,...,176,9367,3660,361,230,19740,16095,6391,2949,35835
57,50,48,1,Texas,Anderson County,4,0,58394,35586,22808,...,178,9449,3634,374,237,19634,15933,6438,2990,35567
76,50,48,1,Texas,Anderson County,5,0,58059,35327,22732,...,190,9389,3575,403,242,19354,15853,6506,3047,35207

In [47]:
#trying to come up with a measure of people in each county per reporting year that do not identify as "white alone" 
#came up with this first before I realized my previous error in not understanding the categories in the data
#tx_race['NW_POP'] = tx_race['TOT_POP'] - tx_race['WA_POP']

tx_race['NOT_ANGLO_POP'] = tx_race['TOT_POP'] - tx_race['NHWA_POP']

In [48]:
tx_race.head(50)

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,BAC_MALE,BAC_FEMALE,AAC_MALE,AAC_FEMALE,NHWA_MALE,NHWA_FEMALE,H_MALE,H_FEMALE,NHWA_POP,NOT_ANGLO_POP
0,50,48,1,Texas,Anderson County,1,0,58458,35521,22937,...,9346,3633,357,224,19751,16105,6363,2924,35856,22602
19,50,48,1,Texas,Anderson County,2,0,58452,35518,22934,...,9346,3633,357,224,19748,16102,6363,2924,35850,22602
38,50,48,1,Texas,Anderson County,3,0,58493,35542,22951,...,9367,3660,361,230,19740,16095,6391,2949,35835,22658
57,50,48,1,Texas,Anderson County,4,0,58394,35586,22808,...,9449,3634,374,237,19634,15933,6438,2990,35567,22827
76,50,48,1,Texas,Anderson County,5,0,58059,35327,22732,...,9389,3575,403,242,19354,15853,6506,3047,35207,22852
95,50,48,1,Texas,Anderson County,6,0,57960,35315,22645,...,9356,3580,404,249,19291,15695,6556,3121,34986,22974
114,50,48,1,Texas,Anderson County,7,0,57829,35350,22479,...,9468,3573,408,221,19187,15506,6621,3180,34693,23136
133,50,48,1,Texas,Anderson County,8,0,57639,35268,22371,...,9439,3569,411,213,19010,15326,6756,3274,34336,23303
152,50,48,1,Texas,Anderson County,9,0,57526,35003,22523,...,9282,3578,441,273,18863,15355,6744,3345,34218,23308
171,50,48,1,Texas,Anderson County,10,0,58175,35615,22560,...,9570,3663,471,275,18997,15259,6925,3414,34256,23919
190,50,48,1,Texas,Anderson County,11,0,57974,35545,22429,...,9623,3601,472,281,18828,15122,6973,3474,33950,24024
209,50,48,1,Texas,Anderson County,12,0,57735,35474,22261,...,9627,3573,479,278,18681,14957,7020,3490,33638,24097
228,50,48,3,Texas,Andrews County,1,0,14786,7368,7418,...,150,144,64,62,3474,3630,3655,3540,7104,7682
247,50,48,3,Texas,Andrews County,2,0,14786,7368,7418,...,150,144,64,62,3474,3630,3655,3540,7104,7682
266,50,48,3,Texas,Andrews County,3,0,14849,7400,7449,...,158,169,61,66,3481,3638,3679,3558,7119,7730
285,50,48,3,Texas,Andrews County,4,0,15386,7690,7696,...,164,163,75,70,3482,3655,3944,3779,7137,8249
304,50,48,3,Texas,Andrews County,5,0,16105,8135,7970,...,212,194,85,74,3509,3672,4321,4013,7181,8924
323,50,48,3,Texas,Andrews County,6,0,16779,8533,8246,...,220,200,83,74,3545,3664,4683,4299,7209,9570
342,50,48,3,Texas,Andrews County,7,0,17435,8930,8505,...,244,219,78,78,3609,3687,5012,4520,7296,10139
361,50,48,3,Texas,Andrews County,8,0,18072,9297,8775,...,245,220,84,79,3648,3716,5336,4773,7364,10708
380,50,48,3,Texas,Andrews County,9,0,17791,9100,8691,...,240,215,82,73,3534,3639,5247,4766,7173,10618
399,50,48,3,Texas,Andrews County,10,0,17603,8958,8645,...,246,226,96,89,3485,3626,5148,4712,7111,10492
418,50,48,3,Texas,Andrews County,11,0,18011,9221,8790,...,260,210,95,87,3543,3641,5336,4851,7184,10827
437,50,48,3,Texas,Andrews County,12,0,18705,9568,9137,...,272,230,89,82,3710,3751,5508,5082,7461,11244
456,50,48,5,Texas,Angelina County,1,0,86771,42515,44256,...,6553,7299,480,564,26735,28238,8899,8246,54973,31798
475,50,48,5,Texas,Angelina County,2,0,86771,42515,44256,...,6553,7299,480,564,26735,28238,8899,8246,54973,31798
494,50,48,5,Texas,Angelina County,3,0,86905,42574,44331,...,6584,7323,471,563,26719,28249,8959,8294,54968,31937
513,50,48,5,Texas,Angelina County,4,0,87297,42813,44484,...,6657,7333,496,576,26682,28198,9151,8470,54880,32417
532,50,48,5,Texas,Angelina County,5,0,87509,42788,44721,...,6592,7396,499,578,26546,28159,9318,8697,54705,32804
551,50,48,5,Texas,Angelina County,6,0,87312,42746,44566,...,6660,7404,523,593,26331,27848,9379,8823,54179,33133
570,50,48,5,Texas,Angelina County,7,0,87567,42770,44797,...,6734,7443,553,611,26124,27822,9528,9024,53946,33621
589,50,48,5,Texas,Angelina County,8,0,87829,42898,44931,...,6708,7455,623,635,26040,27721,9717,9219,53761,34068
608,50,48,5,Texas,Angelina County,9,0,87682,42861,44821,...,6694,7423,596,627,25945,27524,9806,9348,53469,34213
627,50,48,5,Texas,Angelina County,10,0,87572,42720,44852,...,6652,7450,625,645,25775,27373,9884,9504,53148,34424
646,50,48,5,Texas,Angelina County,11,0,86810,42361,44449,...,6689,7433,551,600,25446,26998,9918,9534,52444,34366
665,50,48,5,Texas,Angelina County,12,0,86715,42353,44362,...,6773,7483,564,602,25231,26716,10020,9680,51947,34768
684,50,48,7,Texas,Aransas County,1,0,23158,11485,11673,...,234,182,263,279,8055,8327,2878,2812,16382,6776
703,50,48,7,Texas,Aransas County,2,0,23158,11485,11673,...,234,182,263,279,8055,8327,2878,2812,16382,6776
722,50,48,7,Texas,Aransas County,3,0,23181,11504,11677,...,242,199,262,271,8058,8320,2882,2821,16378,6803
741,50,48,7,Texas,Aransas County,4,0,23216,11517,11699,...,251,210,269,278,7927,8220,3012,2934,16147,7069
760,50,48,7,Texas,Aransas County,5,0,23459,11649,11810,...,274,224,261,285,7983,8340,3068,2905,16323,7136
779,50,48,7,Texas,Aransas County,6,0,23889,11875,12014,...,279,226,276,294,8055,8360,3198,3083,16415,7474
798,50,48,7,Texas,Aransas County,7,0,24566,12227,12339,...,335,261,277,282,8165,8553,3384,3179,16718,7848
817,50,48,7,Texas,Aransas County,8,0,24800,12375,12425,...,339,259,286,283,8242,8547,3443,3280,16789,8011
836,50,48,7,Texas,Aransas County,9,0,25162,12481,12681,...,343,268,271,269,8326,8686,3486,3383,17012,8150
855,50,48,7,Texas,Aransas County,10,0,25392,12573,12819,...,334,274,274,284,8317,8778,3593,3419,17095,8297
874,50,48,7,Texas,Aransas County,11,0,23446,11593,11853,...,319,226,260,268,7664,8160,3306,3135,15824,7622
893,50,48,7,Texas,Aransas County,12,0,23510,11633,11877,...,321,233,269,295,7603,8107,3384,3176,15710,7800
912,50,48,9,Texas,Archer County,1,0,9054,4563,4491,...,42,37,17,22,4103,4085,372,303,8188,866
931,50,48,9,Texas,Archer County,2,0,9061,4566,4495,...,42,37,17,22,4106,4089,372,303,8195,866

In [49]:
tx_race_cnty1 = tx_race[tx_race.NHWA_POP < tx_race.NOT_ANGLO_POP]
tx_race_cnty2 = tx_race[tx_race.NHWA_POP > tx_race.NOT_ANGLO_POP]

In [50]:
tx_race_cnty_not_anglo = tx_race_cnty1[['COUNTY', 'CTYNAME', 'YEAR', 'TOT_POP', 'NHWA_POP','NOT_ANGLO_POP']]
tx_race_cnty_anglo = tx_race_cnty2[['COUNTY', 'CTYNAME', 'YEAR', 'TOT_POP', 'NHWA_POP','NOT_ANGLO_POP']]

In [51]:
#(tx_race.NHWA_POP < tx_race.NOT_ANGLO_POP).sum()

In [52]:
# here is my new dataframe representing counties that are majority not Anglo
tx_race_cnty_not_anglo

       COUNTY         CTYNAME  YEAR  TOT_POP  NHWA_POP  NOT_ANGLO_POP
228         3  Andrews County     1    14786      7104           7682
247         3  Andrews County     2    14786      7104           7682
266         3  Andrews County     3    14849      7119           7730
285         3  Andrews County     4    15386      7137           8249
304         3  Andrews County     5    16105      7181           8924
...       ...             ...   ...      ...       ...            ...
57817     507   Zavala County     8    12310       693          11617
57836     507   Zavala County     9    12121       641          11480
57855     507   Zavala County    10    11957       594          11363
57874     507   Zavala County    11    11969       594          11375
57893     507   Zavala County    12    11840       577          11263

[973 rows x 6 columns]

In [53]:
#counties with majority anglo population
tx_race_cnty_anglo

       COUNTY          CTYNAME  YEAR  TOT_POP  NHWA_POP  NOT_ANGLO_POP
0           1  Anderson County     1    58458     35856          22602
19          1  Anderson County     2    58452     35850          22602
38          1  Anderson County     3    58493     35835          22658
57          1  Anderson County     4    58394     35567          22827
76          1  Anderson County     5    58059     35207          22852
...       ...              ...   ...      ...       ...            ...
57361     503     Young County     8    18163     14296           3867
57380     503     Young County     9    18098     14196           3902
57399     503     Young County    10    17922     13969           3953
57418     503     Young County    11    17986     13946           4040
57437     503     Young County    12    18010     13853           4157

[2075 rows x 6 columns]